networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.55.1
        subnet: 192.168.55.0/24
      driver: default
services:
  node0:
    build: .
    environment:
      ALGORITHM: echo
      EMPTY: null
      PID: 0
      TOPOLOGY: topologies/echo.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.10
    ports:
    - 9090:9090
  node1:
    build: .
    environment:
      ALGORITHM: echo
      EMPTY: null
      PID: 1
      TOPOLOGY: topologies/echo.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.11
    ports:
    - 9091:9091
version: '3.7'
x-common-variables:
  EMPTY: null
  TOPOLOGY: topologies/echo.yaml
